{
  config,
  lib,
  pkgs,
  self',
  ...
}:

with lib;

let
  cfg = config.services.parados;

  mkUserConf = name: userOpts: ''
    user=${name}
    pass=${if userOpts.password != null then userOpts.password else ""}
    ${concatMapStringsSep "\n" (dir: "allow=${dir}") userOpts.allow}
  '';

  settingsConfig = generators.toKeyValue { } cfg.settings;

  configFile = pkgs.writeText "parados.conf" ''
    # Generated by Home Manager parados service module.

    # Core Settings
    ${settingsConfig}

    # Users
    ${concatStringsSep "\n" (mapAttrsToList mkUserConf cfg.users)}
  '';

in
{
  options.services.parados = {
    enable = mkEnableOption "the Parados media server";

    package = mkOption {
      type = types.package;
      default = self'.packages.parados;
      description = "The parados package to use.";
    };

    settings = mkOption {
      description = "Arbitrary configuration options for parados.conf.";
      type = types.submodule {
        freeformType =
          with types;
          attrsOf (oneOf [
            str
            int
            bool
          ]);
      };
      default = {
        media_dir = "${config.home.homeDirectory}/media";
        server_addr = "127.0.0.1";
        server_port = 8088;
        verbose_log = false;
        http_io_timeout = 5;
        max_clients = 64;
        auth_delay = 250;
      };
    };

    users = mkOption {
      description = "User accounts configuration.";
      default = { };
      type = types.attrsOf (
        types.submodule {
          options = {
            password = mkOption {
              type = types.nullOr types.str;
              default = null;
            };
            allow = mkOption {
              type = types.listOf types.str;
              default = [ "*" ];
            };
          };
        }
      );
    };
  };

  config = mkIf cfg.enable {
    home.packages = [ cfg.package ];

    systemd.user.services.parados = mkIf pkgs.stdenv.isLinux {
      Unit = {
        Description = "Parados Media Server Daemon";
        After = [ "network.target" ];
      };
      Service = {
        ExecStart = "${cfg.package}/bin/parados";
        Environment = [ "PARADOS_CONFIG=${configFile}" ];
        Restart = "on-failure";
      };
      Install = {
        WantedBy = [ "default.target" ];
      };
    };

    launchd.agents.parados = mkIf pkgs.stdenv.isDarwin {
      enable = true;
      config = {
        ProgramArguments = [
          "/usr/bin/env"
          "${cfg.package}/bin/parados"
        ];
        EnvironmentVariables = {
          PARADOS_CONFIG = "${configFile}";
          USER = "${config.home.username}";
          HOME = "${config.home.homeDirectory}";
          LOGNAME = "${config.home.username}";
        };
        KeepAlive = true;
        RunAtLoad = true;

        StandardOutPath = "/tmp/parados.out.log";
        StandardErrorPath = "/tmp/parados.err.log";
      };
    };
  };
}
